openapi: 3.0.0
info:
  title: Nodejs-REST-API
  description: Nodejs RESTful API Application using Express JS & Mongo DB
  version: 1.0.0
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Authentication
    description: Authentication Functionality in RESTful API Express JS App
  - name: Products
    description: CRUD Opreations for Product
  - name: Users
    description: CRUD Opretions for User
paths:
  /api/v1/auth/register:
    post:
      tags:
        - Authentication
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: samir
                email: samir@gmail.com
                password: '123456'
                role: admin
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - Authentication
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: osama@gmail.com
                password: '123456'
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/me:
    get:
      tags:
        - Authentication
      summary: Get Authenticated User
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/logout:
    post:
      tags:
        - Authentication
      summary: Logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ''
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/forgot-password:
    post:
      tags:
        - Authentication
      summary: Forgot Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: osama@gmail.com
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/reset-password/8a782dbf4e4bb6b08d7b948fee47484d6f94103bd03f0817cd2939a9cfa88b57:
    post:
      tags:
        - Authentication
      summary: Reset Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                password: '1234567'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/update-password:
    post:
      tags:
        - Authentication
      summary: Update Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                oldPassword: '123456'
                newPassword: '12345678910'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/products/65a18e3deac6342746358410:
    get:
      tags:
        - Products
      summary: Get Product
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Products
      summary: Update Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: product name updated
                description: product 2 updated
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/products:
    get:
      tags:
        - Products
      summary: Get All Products
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: select
          in: query
          schema:
            type: string
          example: name,description
        - name: sort
          in: query
          schema:
            type: string
          example: name
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Products
      summary: Create Product
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: amgad
                description:
                  type: string
                  example: product 2
                file:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: Content-Type
          in: header
          schema:
            type: string
          example: multipart/form-data
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/products/6599efd6f69ac9f5d8ff3df3:
    delete:
      tags:
        - Products
      summary: Delete Product
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/users/65974f5f709683022f1ea7f9:
    get:
      tags:
        - Users
      summary: Get User
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/users:
    get:
      tags:
        - Users
      summary: Get All Users
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Users
      summary: Create User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: alimahmoud22
                email: ali_mahmoud22@gmail.com
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/users/659844e191fb14a3ea000855:
    put:
      tags:
        - Users
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: ahmed11
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/users/6599f103493244628bdbafde:
    delete:
      tags:
        - Users
      summary: Delete User
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
